# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


stages:
  - stage: BuildApp
    displayName: Build App

    jobs:
      - job: 'NodeBuild'
        pool:
          name: szecsikr
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '20.x'
          displayName: 'Install Node.js'

        - script: |
            cd frontend/chat-app
            npm install
            npm run build
          displayName: 'npm install and build'

      - job: 'DockerBuild'
        pool:
          name: szecsikr
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce' # string. Required. Docker Version. Default: 17.09.0-ce.
            #releaseType: 'stable' # 'stable' | 'edge' | 'test' | 'nightly'. Release type. Default: stable.
        - script: |
            docker login -u $(dockerhub-user) -p $(dockerhub-pw)
        - task: Docker@2
          inputs:
            repository: 'szecsikr/chatapp-backend'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
  - stage: DeployDev
    displayName: DeployDev
    pool:
      name: szecsikr
    jobs:
    - deployment: dev
      environment:
        name: szecsikr
        resourceType: Kubernetes
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              name: bake
              displayName: Bake K8s manifests from Helm chart
              inputs:
                action: bake
                helmChart: chatapp-backend
                overrides: |
                  image.repository:szecsikr/chatapp-backend
                  image.tag:69
            - task: KubernetesManifest@0
              displayName: Deploy K8s manifests
              inputs:
                namespace: default
                manifests: $(bake.manifestsBundle)
                rolloutStatusTimeout: 120
                releaseName: backend
