apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  tls:
  - hosts:
    - 4.182.134.120
  rules:
  - host: http://4.182.134.120/
    http:
      paths:
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: {{ include "backend.fullname" . }}
            port:
              number: 80